version: "3.8"
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_API_KEY=your_key
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm run start"
