export const charactersData = [
  {
    name: "Dr. Elena Pierce",
    profession: "Strategic Consultant",
    personality: "INTJ",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Liam Foster",
    profession: "Theoretical Physicist",
    personality: "INTP",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Claire Bennett",
    profession: "Psychologist",
    personality: "INFJ",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Noah Sinclair",
    profession: "Writer",
    personality: "INFP",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Sophia Reed",
    profession: "Creative Director",
    personality: "ENTP",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Ethan Blake",
    profession: "Corporate Executive",
    personality: "ENTJ",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Isabella Tran",
    profession: "Public Relations Manager",
    personality: "ENFJ",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Lucas Meyer",
    profession: "Motivational Speaker",
    personality: "ENFP",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Olivia Carson",
    profession: "Nurse",
    personality: "ISFJ",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Aiden Murphy",
    profession: "IT Support Specialist",
    personality: "ISTJ",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Evan Carter",
    profession: "Mechanical Engineer",
    personality: "ISTP",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Mason King",
    profession: "Social Worker",
    personality: "ISFP",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Chloe Rivera",
    profession: "Interior Designer",
    personality: "ESFP",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Jackson Moore",
    profession: "Paramedic",
    personality: "ESTP",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Natalie Cooper",
    profession: "Elementary School Teacher",
    personality: "ESFJ",
    opinion_strength: 0,
    additional_info: "",
  },
  {
    name: "Henry Walsh",
    profession: "Military Officer",
    personality: "ESTJ",
    opinion_strength: 0,
    additional_info: "",
  },
];
